# Generated by Django 3.0.7 on 2021-09-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(default='Test 7-9-2021 1:39:0', max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_time', models.FloatField(max_length=6)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('access_password', models.CharField(blank=True, max_length=10, unique=True)),
                ('topic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='questions_generator.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField(choices=[(1, 'Writing'), (2, 'Multiple Choice')], default=1)),
                ('question_title', models.CharField(max_length=300)),
                ('question_level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Advanced')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='question', to='questions_generator.Quizes')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.CharField(max_length=300)),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='questions_generator.Questions')),
            ],
        ),
    ]
