# Generated by Django 3.0.7 on 2021-09-08 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions_generator', '0002_auto_20210908_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='is_active',
        ),
        migrations.AddField(
            model_name='quizes',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='access_password',
            field=models.CharField(blank=True, default=uuid.UUID('8569619c-10b1-11ec-a1de-34415d7ef84b'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='exam_title',
            field=models.CharField(default='New_Quiz_892021203157', max_length=200),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='organization',
            field=models.CharField(default='Test Examination', max_length=400),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
