# Generated by Django 3.0.7 on 2021-09-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_generator', '0003_auto_20210908_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questions_generator.Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questions_generator.Quizes'),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='access_password',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quizes',
            name='exam_title',
            field=models.CharField(default='New Quiz', max_length=200),
        ),
    ]
